### ISSUE TITLE
computation via alloscore and distfromq

### ISSUE THREAD

**Issue by aaronger** [aaronger/utility-eval-papers#51]
Let's consolidate issues #13 and #14 here.  The questions are whether, where, and how to explain the computation of allocation scores from hub hosp quantile forecasts.
- whether: seems necessary.  I'd rather not just say "it's all in the code repos" even if reviewers let it slide.
- where: seems like after `\paragraph{Step 3: Define the scoring rule.}` and/or in `\subsubsection{Allocation Score}` would be the natural insertion points for the current draft.  But maybe this needs a new section?
- how: definitely only a sketch in the text.  Some more detail in the supplement. Wondering though if an iteration picture like [the one in my slides](https://github.com/aaronger/utility-eval-papers/blob/main/talks/plots/output/iter_combo.png) would be appropriate or useful.

**Comment by elray1** [comment]
I agree that we should do this.  r.e. where, in part I think that the distfromq piece is just an add-on that is specific to our application.  We don't talk about the fact that our application is working with quantile forecasts until the application section.  So I might add the discussion about distfromq somewhere after that?

**Comment by aaronger** [comment]
And then maybe after the distfromq distributions are described we can talk about using them to iterate through allocations with alloscore...

**Comment by elray1** [comment]
just noting that currently the only discussion of this sits in the supplement but it seems important to mention this at some level in the main text too

**Comment by aaronger** [comment]
Well, stuff is there now... not sure how much easier it makes mentioning this in the main text.
