### ISSUE TITLE
Figure 2: Hospitalization data and example forecasts

### ISSUE THREAD

**Issue by aaronger** [aaronger/utility-eval-papers#57]
[This](https://github.com/aaronger/utility-eval-papers/blob/8b10ba67e053e72793f7a3e277b7e723ce6794b5/alloscore_manuscript/alloscore-application.Rnw#L341) could be 2 states, which might better sync with allocation context. 
Example: [https://github.com/aaronger/utility-eval-papers/blob/main/talks/plots/output/p_VA_JHU_MUNI.png](https://github.com/aaronger/utility-eval-papers/blob/main/talks/plots/output/p_VA_JHU_MUNI.png)

**Comment by nickreich** [comment]
flagging that this is maybe a "nice-to-have" for the preprint submission, but not essential.

**Comment by elray1** [comment]
I am cutting this figure from my abbreviated version of the article, since it's similar to, but less-informative than, figure 3.
