### ISSUE TITLE
Table 1 cleanup

### ISSUE THREAD

**Issue by elray1** [aaronger/utility-eval-papers#59]
In table 1 (on application branch), table headings are "model, alloscore, allo_rank, mwis, mwis_rank".  I realize this is just a draft, but am filing this while I'm thinking about it.  notes:

- "alloscore" vs "allo"
- underscores
- prefixing an "m" for mean on WIS, but not on alloscore

**Comment by nickreich** [comment]
in addition to the above, Table 1 needs a caption.

**Comment by nickreich** [comment]
Noting that for a single date, a justification could be made to include "m" on WIS but not on allocation score: the AS is defined across a set of locations whereas the WIS is defined for one location and we take the mean across all of those locations to get the reported score. But in table 1, we are taking the mean across multiple dates...
