### ISSUE TITLE
add citation to supplement section 3

### ISSUE THREAD

**Issue by elray1** [aaronger/utility-eval-papers#61]
In supplement section 3, "[w]e recall how quantiles arise as solutions to a probabilistic decision problem."  Let's add a citation to the literature that we're recalling.

**Comment by elray1** [comment]
it seems like we should somehow concretely indicate that this is a longstanding known fact... at minimum, I think Murphy(1993) has some kind of statement of this

**Comment by aaronger** [comment]
But that's for a discrete problem... It's the continuous situation that's hard to reference.  I wish Ehm et al. (2016) had done this in sec 2.3, but they really didn't.

**Comment by elray1** [comment]
That makes sense.  Can we say something about how for discrete problems this is well known (e.g., cite), and it seems to be understood as true in a continuous setting as well though we are not aware of a specific citation, so we lay out out here?

**Comment by aaronger** [comment]
I'm torn.  On the one hand, I don't want to look like I'm trying to recycle content that Dawid or Gneiting would say is common knowledge as original, but I also feel like the presentation and level of detail might be novel.  There is the stochastic optimization literature, but will take some time to find a sufficiently non-quirky source...

**Comment by elray1** [comment]
I'm not saying you have to attribute your work to someone else, but I think we need to do something to say how the content of this section fits into or complements what's out there in existing literature

**Comment by aaronger** [comment]
How about Gneiting "Quantiles as optimal point forecasts" and/or Jose Winkler "Evaluating Quantile Assessments" along with a "see references therein"...

**Comment by elray1** [comment]
sounds good to me
