### ISSUE TITLE
more specificity r.e. sets that x and y belong to in supplement section 3?

### ISSUE THREAD

**Issue by elray1** [aaronger/utility-eval-papers#62]
We currently say that x and y are elements of R.  Should we say that they are in R^+?

**Comment by aaronger** [comment]
I think everything continues to work if you allow negative procurement = selling.  Don't want to talk about this but also don't want to make quantiles sound like they only exist for positive RVs.

**Comment by elray1** [comment]
ok, but we do mention R_+^N some time later on

**Comment by aaronger** [comment]
OK, I actually changed this while reverting a few changes in the beginning of the quantile section 57131c9825ab2637715a700e2e02fd0d03b9b9b4
