### ISSUE TITLE
supplement: double check derivative sides in Eq (24)

### ISSUE THREAD

**Issue by elray1** [aaronger/utility-eval-papers#64]
We have the following written in the supplement:
![image](https://github.com/aaronger/utility-eval-papers/assets/5132208/cf45b515-dec3-40c9-862c-959baac6f91f)

For the left hand side (involving i), writing out one intermediate step this is
$$-\left( E_{F_i}[(Y_i - x_i^\star)\_+ - (Y_i - (x_i^\star + \delta))\_+)]   \right),$$
which matches the set up for $D_+$ above (and similarly, the right hand side seems to match the setup for $D_-$):
![image](https://github.com/aaronger/utility-eval-papers/assets/5132208/c4702633-d19f-41ec-a57d-7990a5ab715c)

**Comment by aaronger** [comment]
I think the problem is that I didn't apply the parentheses correction I made for (2) and (7) also to (23).
