### ISSUE TITLE
supplement: clarify reasoning for claim that "a single number" exists satisfying inequalities for Lagrange multiplier

### ISSUE THREAD

**Issue by elray1** [aaronger/utility-eval-papers#65]
Looking at this section of the supplement:
![image](https://github.com/aaronger/utility-eval-papers/assets/5132208/564c58ad-1e95-408b-af96-7156744b4451)

The claim that "a single number" exists such that these inequalities are satisfied is not obvious to me -- for example, what if all marginal distributions are discrete and have a jump at $x_i^\star$?  Can we either update the language to remove the word "single" or add more of an explanation for the "Therefore"?

**Comment by aaronger** [comment]
Yes definitely not unique.  Will try "independent of i"?
