### ISSUE TITLE
supplement: consider clarifications r.e. TQ, F_T

### ISSUE THREAD

**Issue by elray1** [aaronger/utility-eval-papers#66]
Optionally, there are two things I thought it might be helpful to add to supplement section 4 around the discussion of TQ, $F_T$, etc.:

1. State that we're using "T" to stand for "total"
2. Note that $F_T$ is the distribution that arises from summing the marginal quantile sets, but this is not the same as the distribution of the total across all locations. In particular, we are not doing computations here that account for dependence among the locations.  Is it the distribution that would arise if we assumed exact dependence among the locations (i.e., something like Kendall's tau = 1)?

**Comment by aaronger** [comment]
Yeah I think exact dependence is what you get from making every coordinate a quantile transformation of a single $U \sim \mathrm{Uninf}[0,1]$

**Comment by aaronger** [comment]
Adding a note about "totalling"...
