### ISSUE TITLE
Consider removing section 2.3.2, connections between scores

### ISSUE THREAD

**Issue by elray1** [aaronger/utility-eval-papers#68]
Not a strong opinion -- but on a re-read, I'm not sure that content is really critical here?  We say a bit about the set up for WIS in the previous section of the main text and go into a lot of depth in the supplement.

**Comment by nickreich** [comment]
I don't have a strong feeling on doing this or not before preprint submission.

**Comment by nickreich** [comment]
does suggest that this might be a place to cut text if we were needing to trim down length

**Comment by elray1** [comment]
I removed this from the shorter version of the manuscript.
